### ISSUE TITLE
Model Download link not working 

### ISSUE THREAD

**Issue by jaschahuisman** [m1guelpf/whisper-cli-rs#11]
Hello, first of all: thank you for all the work that went into this rust cli!

The model download fails in the `Model` [`download`](https://github.com/m1guelpf/whisper-cli-rs/blame/9f653170b323805efb3bc55c9b4d5b7a3d1bf4aa/src/model.rs#L91) function. 

The hardcoded url (`https://huggingface.co/datasets/ggerganov/whisper.cpp/resolve/main/ggml-{}.bin`) leads to a page giving a 404 with response message: `Repository not found`. 

I suggest using something else, for example:

`https://huggingface.co/ggerganov/whisper.cpp/blob/main/ggml-{}.bin`

@m1guelpf

**Comment by m1guelpf** [comment]
Fixed in 088b587
