### ISSUE TITLE
Use all system threads

### ISSUE THREAD

**Issue by sloganking** [m1guelpf/whisper-cli-rs#7]
On my 8 core, 16 thread machine. This program only utilizes 4 threads.

**Comment by sloganking** [comment]
`whisper.cpp`'s CLI implementation defaults to using 4 threads. I suspect we just need to override that value with `num_cpus::get()` from the [num_cpus](https://crates.io/crates/num_cpus) crate.

**Comment by sloganking** [comment]
Their multi-thread implementation seems very inefficient. I get worse performance if I use all my cores than if I use only some of them.

Here's my own benchmarks after applying the edit mentioned above to this repo, and doing some testing:

Threads: `1` - Time: `65.216966095s`
Threads: `2` - Time: `39.761959427s`
Threads: `3` - Time: `26.631611589s`
Threads: `4` - Time: `21.756073009s`
Threads: `6` - Time: `18.685812368s`
Threads: `8` - Time: `15.914378154s`
Threads: `10` - Time: `16.391568555s`
Threads: `12` - Time: `14.020055631s`
Threads: `14` - Time: `15.498474867s`
Threads: `16` - Time: `16.786118358s`

My machine has 8 physical cores and 16 total logical threads. My performance decreases after I use more than my physical thread count. Because of this, perhaps we should use `num_cpus::get_physical() instead of `num_cpus::get()`

**Comment by m1guelpf** [comment]
Tried on my local computer and using either is slower than not doing it at all, closing for now.
